name: Example Callable Workflow

on:
  workflow_call:
    inputs:
      favouriteFruit:
        required: true
        type: string

    secrets:
      exampleSecretVariable:
        required: true

jobs:
  callable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm that the job runs
        run: echo "Hello, world!"
      - name: Log the workflow inputs
        run: echo "Input of favouriteFruit has value of ${{inputs.favouriteFruit}}"
      - name: Log the workflow secrets
        run: echo "Secret of exampleSecretVariable has value of ${{secrets.exampleSecretVariable}}"